#!/usr/bin/env bash

##
# Mocks the output and return value of a given function.
##
bash_test::mock() {
    local mock="${1:?"A method name to mock is required"}"

    ##
    # Defines the mocking function with available values.
    ##
    __bash_test::mock() { echo "{{2}}" && return {{3}}; }

    # redefine the mocking function with the given mocked function name
    eval "$(
        declare -f __bash_test::mock \
            | sed "s/^__bash_test::mock/$mock/" \
            | sed "s|{{2}}|${2}|;s|{{3}}|${3}|"
    )"
}
