#!/usr/bin/env bash

source "$FEATURE/test-feature" "$tomchkk_private_projects_bash_clash/src/index"

##
# Cats the command's usage documentation.
##
__app_command::usage() {
    cat << EOF

$APP_NAME ($APP_VERSION)

A test-running suite for Bash.

Usage:  $APP_NAME [options] <path|directory>

Options:
    -e, --exclude <pattern>     Exclude tests from a test run
    -f, --filter <pattern>      Filter tests in a test run
    -h, --help                  Print usage information

EOF
}

##
# Handles incoming command requests.
##
__app_command::handle() {
    local exclude
    local filter
    local path

    while [[ "$#" -gt 0 ]]; do
        case $1 in
            -e|--exclude)
                exclude="--exclude=$2" && shift
            ;;
            -f|--filter)
                filter="--filter=$2" && shift
            ;;
            -h|-*|--help|--*)
                __app_command::usage && return 0
            ;;
            *)
                path="$1"
            ;;
        esac

        shift
    done

    if [[ -z "$path" ]] || [[ ! -e "$path" ]]; then
        __app_command::usage && return 0
    fi

    test_feature::test "$path" "$filter" "$exclude"
}

# handle empty args
[[ -z "$@" ]] && set -- "--help"

__app_command::handle $@
