#!/usr/bin/env bash

__bash_test_dir="${1:?"The app directory is required"}"
__bash_test_autoloader="${2:?"The autoloader path is required"}"
__bash_test_args=${@:3}

APP_VERSION="$(
    cd "$__bash_test_dir"
    git describe --always --first-parent HEAD 2>/dev/null || echo "v0.0.0"
)"

source "$__bash_test_dir/.env"

APP_NAME="${APP_NAME:-$(basename ${BASH_SOURCE[0]})}"

source "$__bash_test_autoloader"

__bash_test_src="$__bash_test_dir/src"

source "$__bash_test_src/kernel" "$__bash_test_args"
