#!/usr/bin/env bash

__bash_test_dir="${1:?"The app directory is required"}"
__bash_test_args=${@:2}

APP_VERSION="$(cat $__bash_test_dir/version)"

source "$__bash_test_dir/.env"

APP_NAME="${APP_NAME:-$(basename ${BASH_SOURCE[0]})}"

__bash_test_src="$__bash_test_dir/src"

source "$__bash_test_src/kernel" "$__bash_test_args"
