#!/usr/bin/env bash

echo "Bash Test - $(git describe --always --first-parent HEAD)" && echo

source ./submodules/autoload

__bash_test_dir="$(dirname ${BASH_SOURCE[0]})"

__bash_test_args=(
    "$__bash_test_dir/src/bash-assert"
    "$tomchkk_private_projects_bash_clash/src/index"
)
source "$__bash_test_dir/src/bash-test" "${__bash_test_args[@]}"

bash_test::run $@

echo
