#!/usr/bin/env bash

source "$SERVICE/bash-test"

##
# Runs tests in the given path and filter.
##
test_feature::test() {
    local path="${1:?"A file or directory is required"}"
    local options="${@:2}"

    __test_feature::print_header
    bash_test::run $path ${options[@]}
    __test_feature::print_footer
}

##
# Prints test run header.
##
__test_feature::print_header() {
    cat <<HEAD
$APP_NAME - $APP_VERSION

HEAD
}

##
# Prints test run footer.
##
__test_feature::print_footer() {
    cat <<FOOT

FOOT
}
