#!/usr/bin/env bash

##
# Tests that the give parameters are equivalent.
##
bash_assert::assert_equals() {
    local expected=${1:?"An expected value must be set"}
    local actual=${2:?"An actual value must be set"}

    if [[ $expected == $actual ]]; then
        bash_test::pass

        return 0
    fi

    bash_test::fail "$expected" "$actual"

    return 1
}
